### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by Feng0-0** [BioMedicalBigDataMiningLab/TDRC#1]
您好！很感谢您的工作，给了我很大的启发。

我在复现您的实验，但是由于缺少您数据集中HMDD2.0的Disease name和miRNA name 没有办法在我的模型上实现，不知您是否方便把数据发学生一份，不胜感激。

祝：生活愉快！

联系方式：1019372223@qq.com

**Comment by fhuang233** [comment]
好的，我们已经给您发到邮箱中，也一并更新了这里的文件，为我们的疏忽给您带来的不便感到抱歉。

**Comment by Feng0-0** [comment]
> 好的，我们已经给您发到邮箱中，也一并更新了这里的文件，为我们的疏忽给您带来的不便感到抱歉。

已经收到！感谢你们的杰出工作！谢谢！
